import { describe, it, expect } from "vitest";
import { stripSignature } from "../../src/utils/signature-stripper";

describe("stripSignature", () => {
  it("drops a lone trailing 'Best,' paragraph", () => {
    const html = "<p>I see only one event notification definition.</p><p>Best,</p>";
    const out = stripSignature(html);
    expect(out).not.toMatch(/Best,/);
    expect(out).toMatch(/notification definition/);
  });

  it("drops 'Best,<br/>Aviv' style closing+name signature", () => {
    const html =
      "<p>I believe this is related to the IO pattern.</p><p>Best,<br/>Aviv</p>";
    const out = stripSignature(html);
    expect(out).not.toMatch(/Best,/);
    expect(out).not.toMatch(/Aviv/);
    expect(out).toMatch(/IO pattern/);
  });

  it("drops a contact-line signature block (Efi's pattern)", () => {
    const html =
      "<p>That's the one we are talking about.</p>" +
      "<p><b>Efi Sandler</b><br/>Technical Support Manager, Americas.<br/>Silk · <a href='https://support.silk.us'>https://support.silk.us</a> · +1 781 690 6687</p>";
    const out = stripSignature(html);
    expect(out).not.toMatch(/Efi Sandler/);
    expect(out).not.toMatch(/Technical Support Manager/);
    expect(out).not.toMatch(/\+1 781 690 6687/);
    expect(out).toMatch(/talking about/);
  });

  it("drops mobile-app signatures ('Get Outlook for iOS')", () => {
    const html = "<p>Sure. I'll handle on Sunday.</p><p>Get Outlook for iOS</p>";
    const out = stripSignature(html);
    expect(out).not.toMatch(/Get Outlook/);
    expect(out).toMatch(/handle on Sunday/);
  });

  it("drops Hebrew mobile signature 'השג את Outlook'", () => {
    const html =
      "<p dir='rtl'>היי</p><p dir='rtl'>השג את <a href='https://aka.ms/o0ukef'>Outlook עבור iOS</a></p>";
    const out = stripSignature(html);
    expect(out).not.toMatch(/השג את/);
    expect(out).toMatch(/היי/);
  });

  it("walks back through MULTIPLE signature paragraphs", () => {
    const html =
      "<p>So we have two options.</p>" +
      "<p>Best,</p>" +
      "<p>Aviv</p>";
    const out = stripSignature(html);
    expect(out).not.toMatch(/Best,/);
    expect(out).not.toMatch(/Aviv/);
    expect(out).toMatch(/two options/);
  });

  it("does NOT strip body paragraphs that happen to mention a title", () => {
    const html =
      "<p>We need to hire a Technical Manager to handle this work.</p>" +
      "<p>Please review the proposal.</p>";
    const out = stripSignature(html);
    expect(out).toMatch(/Technical Manager/);
    expect(out).toMatch(/proposal/);
  });

  it("does NOT strip a long final paragraph (probably real content)", () => {
    const longBody =
      "We've received a report from Matthew at Sentara that he is not receiving email notifications generated by the event notification mechanism in Clarity. This is a very long paragraph that describes the actual issue and should never be treated as a signature even though it ends the message.";
    const html = `<p>Hi All,</p><p>${longBody}</p>`;
    const out = stripSignature(html);
    expect(out).toContain(longBody);
  });

  it("preserves a body when there is no signature", () => {
    const html =
      "<p>Hi</p><p>The following test run skip to monitor by user.</p><p>Any idea how to prevent flex moved the volume to detection</p>";
    const out = stripSignature(html);
    expect(out).toBe(html);
  });

  it("handles empty body", () => {
    expect(stripSignature("")).toBe("");
    expect(stripSignature("   ")).toBe("   ");
  });

  it("strips trailing empty paragraphs", () => {
    const html = "<p>Real content</p><p></p><p>   </p>";
    const out = stripSignature(html);
    expect(out).toBe("<p>Real content</p>");
  });

  it("stops at first non-signature when walking back", () => {
    const html =
      "<p>Important paragraph in the middle</p>" +
      "<p>Another paragraph that is real content with full sentences</p>" +
      "<p>Best,</p>";
    const out = stripSignature(html);
    expect(out).toMatch(/Important paragraph/);
    expect(out).toMatch(/Another paragraph/);
    expect(out).not.toMatch(/Best,/);
  });
});
